# -*- coding: utf-8 -*-
"""Krates: 1.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsxujEZPBpoE4DP9e2XJstFn3NETcI2-
"""

nilai = 85

if nilai >= 80:
    print("Krates: Bagus, kamu paham.")
else:
    print("Krates: Coba lagi, kamu bisa lebih baik.")

nilai = 50

if nilai >= 60:
    print("Krates: Bagus, kamu paham.")
else:
    print("Krates: Coba lagi, kamu bisa lebih baik.")

nilai = 75

if nilai >= 80:
    print("Krates: Luar biasa.")
elif nilai >= 60:
    print("Krates: Cukup baik, tapi bisa lebih.")
else:
    print("Krates: Kamu perlu belajar lebih keras.")

for i in range(5):
    print("Krates sedang berpikir... langkah ke-" + str(i))

for i in range(5):
    print("Langkah ke-" + str(i))
    print("Krates sedang menganalisis...")
    print("---")

nilai_argumen = [90, 45, 70, 30, 85]

for nilai in nilai_argumen:
    if nilai >= 80:
        print("Krates: Argumen kuat.")
    elif nilai >= 60:
        print("Krates: Argumen cukup, tapi perlu diperkuat.")
    else:
        print("Krates: Argumen lemah, coba lagi.")

def krates_nilai(argumen):
    if argumen >= 80:
        print("Krates: Argumen kuat.")
    elif argumen >= 60:
        print("Krates: Argumen cukup, tapi perlu diperkuat.")
    else:
        print("Krates: Argumen lemah, coba lagi.")

krates_nilai(90)
krates_nilai(55)
krates_nilai(70)

def krates_nilai(nama, argumen):
    if argumen >= 80:
        print(nama + ", argumen kamu kuat. Saya setuju.")
    elif argumen >= 60:
        print(nama + ", argumen kamu cukup, tapi masih bisa diperkuat.")
    else:
        print(nama + ", argumen kamu lemah. Coba pikirkan lagi.")

krates_nilai("Nio", 90)
krates_nilai("Nio", 55)
krates_nilai("Nio", 70)

pendapat = "setuju"

if pendapat == "setuju":
  print("Oke itu keren")
else:
  print("coba pikir lagi")

def krates_debat(nama, pendapat):
    if pendapat == "setuju":
        print("Nah" + nama + "bagus pikiran mu mulai kritis ")
    elif pendapat == "tidak setuju":
        print("Gini " + nama + "aku rasa kamu coba pikir lagi")
    else:
        print("coba pikir lagi deh " + nama)

krates_debat("Nio ", "setuju")
krates_debat("Nio ", "tidak setuju")
krates_debat("Nio ", "bingung")

memori_krates = {
    "nama": "Nio",
    "topik_favorit": "AI",
    "jumlah_debat": 0
}

print(memori_krates["nama"])
print(memori_krates["topik_favorit"])

memori_krates["mood"] = "penasaran"
memori_krates["jumlah_debat"] = 3

print(memori_krates)

jumlah = 0

while jumlah < 3:
    print("Krates sedang mendengarkan... sesi ke-" + str(jumlah + 1))
    jumlah = jumlah + 1

print("Krates: Sesi selesai.")

print("Krates: Halo, saya Krates. Ketik 'stop' untuk mengakhiri.")

while True:
    input_user = input("Kamu: ")

    if input_user == "stop":
        print("Krates: Sampai jumpa, semoga pikiranmu semakin tajam.")
        break
    elif input_user == "setuju":
        print("Krates: Menarik, tapi apakah kamu sudah mempertimbangkan sisi lain?")
    elif input_user == "tidak setuju":
        print("Krates: Bagus, jelaskan alasanmu.")
    else:
        print("Krates: Hmm, coba elaborasi lebih dalam.")

# Data training sederhana
# [jam_belajar, hasil_ujian]
data = [
    [1, 40],
    [2, 50],
    [3, 60],
    [4, 70],
    [5, 80],
]

# Krates mencari pola
for contoh in data:
    jam = contoh[0]
    nilai = contoh[1]
    print("Belajar " + str(jam) + " jam → nilai " + str(nilai))

from sklearn.linear_model import LinearRegression
import numpy as np

# Data training
jam_belajar = np.array([[1], [2], [3], [4], [5]])
nilai = np.array([40, 50, 60, 70, 80])

# Krates belajar dari data
model = LinearRegression()
model.fit(jam_belajar, nilai)

# Krates prediksi
prediksi = model.predict([[6]])
print("Prediksi nilai untuk 6 jam belajar: " + str(prediksi[0]))

hasil = [90.0]
print(hasil)
print(hasil[0])

# Install dulu
# !pip install transformers torch

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

kalimat = "Democracy is better than autocracy"
tokens = tokenizer(kalimat)

print("Kalimat asli:", kalimat)
print("Token IDs:", tokens["input_ids"])

from transformers import AutoTokenizer, AutoModel
import torch

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

kalimat = "Democracy is better than autocracy"
inputs = tokenizer(kalimat, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

embeddings = outputs.last_hidden_state
print("Bentuk embedding:", embeddings.shape)
print("Angka pertama dari kata 'Democracy':", embeddings[0][1][:5])

# Dataset argumen - dibuat dari filosofi Krates
data_argumen = [
    {"teks": "mencuri itu selalu salah", "kekuatan": "lemah"},
    {"teks": "mencuri roti untuk keluarga yang kelaparan berbeda dengan korupsi", "kekuatan": "kuat"},
    {"teks": "demokrasi lebih baik dari otokrasi", "kekuatan": "lemah"},
    {"teks": "demokrasi memberi ruang manusia belajar dari kesalahannya sendiri", "kekuatan": "kuat"},
    {"teks": "manusia itu jahat", "kekuatan": "lemah"},
    {"teks": "manusia punya moral bawaan tapi bisa terpengaruh konteks", "kekuatan": "kuat"},
]

for argumen in data_argumen:
    print(f"Argumen: {argumen['teks']}")
    print(f"Kekuatan: {argumen['kekuatan']}")
    print("---")

# Dataset argumen - dibuat dari filosofi Krates
data_argumen = [
    {"teks": "mencuri itu selalu salah", "kekuatan": "lemah"},
    {"teks": "mencuri roti untuk keluarga yang kelaparan berbeda dengan korupsi", "kekuatan": "kuat"},
    {"teks": "demokrasi lebih baik dari otokrasi", "kekuatan": "lemah"},
    {"teks": "demokrasi memberi ruang manusia belajar dari kesalahannya sendiri", "kekuatan": "kuat"},
    {"teks": "manusia itu jahat", "kekuatan": "lemah"},
    {"teks": "manusia punya moral bawaan tapi bisa terpengaruh konteks", "kekuatan": "kuat"},
    {"teks": "apakah perdamaian itu ditemukan atau diciptakan", "kekuatan": "kuat"},
    {"teks": "pria lebih hebat dari wanita", "kekuatan": "lemah"},
    {"teks": "orang kulit putih adalah ras terhebat di dunia", "kekuatan": "lemah"},
]

for argumen in data_argumen:
    print(f"Argumen: {argumen['teks']}")
    print(f"Kekuatan: {argumen['kekuatan']}")
    print("---")

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Data training dari dataset kamu
teks = [
    "mencuri itu selalu salah",
    "mencuri roti untuk keluarga yang kelaparan berbeda dengan korupsi",
    "demokrasi lebih baik dari otokrasi",
    "demokrasi memberi ruang manusia belajar dari kesalahannya sendiri",
    "manusia itu jahat",
    "manusia punya moral bawaan tapi bisa terpengaruh konteks",
    "pria lebih hebat dari wanita",
    "orang kulit putih adalah ras terhebat di dunia",
    "apakah perdamaian itu ditemukan atau diciptakan",
]

label = [
    "lemah", "kuat",
    "lemah", "kuat",
    "lemah", "kuat",
    "lemah", "lemah",
    "kuat",
]

# Bangun model Krates
krates_ml = Pipeline([
    ("vectorizer", TfidfVectorizer()),
    ("classifier", MultinomialNB())
])

# Krates belajar dari data
krates_ml.fit(teks, label)

# Test Krates dengan argumen baru
argumen_baru = "semua politisi itu koruptor"
hasil = krates_ml.predict([argumen_baru])
print(f"Argumen: {argumen_baru}")
print(f"Krates menilai: {hasil[0]}")

argumen_baru = "Demokrasi itu kesalahan, karena ibarat kapal jika banyak kepala yang mengatur tidak akan sampai tujuan"
hasil = krates_ml.predict([argumen_baru])
print(f"Argumen: {argumen_baru}")
print(f"Krates menilai: {hasil[0]}")

# Tambah data baru
teks.append("demokrasi itu kesalahan karena ibarat kapal jika banyak kepala yang mengatur tidak akan sampai tujuan")
label.append("kuat")

teks.append("demokrasi itu buruk")
label.append("lemah")

teks.append("otokrasi efektif karena keputusan bisa diambil cepat tanpa perdebatan panjang")
label.append("kuat")

# Train ulang Krates
krates_ml.fit(teks, label)

# Test lagi argumen yang tadi salah
hasil = krates_ml.predict([argumen_baru])
print(f"Setelah ditambah data:")
print(f"Argumen: {argumen_baru}")
print(f"Krates menilai: {hasil[0]}")

from transformers import pipeline

# Krates versi transformer
krates_transformer = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

argumen = "demokrasi itu kesalahan karena ibarat kapal jika banyak kepala yang mengatur tidak akan sampai tujuan"

hasil = krates_transformer(
    argumen,
    candidate_labels=["argumen kuat", "argumen lemah"],
)

print(f"Argumen: {argumen}")
print(f"Krates menilai: {hasil['labels'][0]}")
print(f"Keyakinan: {hasil['scores'][0]:.2%}")

argumen_list = [
    "semua politisi itu koruptor",
    "korupsi terjadi karena sistem yang lemah, bukan karena semua politisi jahat",
    "wanita tidak cocok jadi pemimpin",
    "kepemimpinan tidak ditentukan gender tapi karakter dan kemampuan"
]

for argumen in argumen_list:
    hasil = krates_transformer(
        argumen,
        candidate_labels=["argumen kuat", "argumen lemah"],
    )
    print(f"Argumen: {argumen}")
    print(f"Krates menilai: {hasil['labels'][0]} ({hasil['scores'][0]:.2%})")
    print("---")

argumen = "semua politisi itu koruptor"

hasil = krates_transformer(
    argumen,
    candidate_labels=[
        "pernyataan yang mempertimbangkan konteks dan alasan",
        "pernyataan yang menyimpulkan tanpa bukti atau konteks"
    ],
)

print(f"Argumen: {argumen}")
print(f"Krates menilai: {hasil['labels'][0]}")
print(f"Keyakinan: {hasil['scores'][0]:.2%}")

import requests
import json

def krates_berpikir(argumen_user):
    # Langkah 1: ML nilai argumen dulu
    hasil_ml = krates_transformer(
        argumen_user,
        candidate_labels=[
            "pernyataan yang mempertimbangkan konteks dan alasan",
            "pernyataan yang menyimpulkan tanpa bukti atau konteks"
        ]
    )

    label = hasil_ml["labels"][0]
    keyakinan = hasil_ml["scores"][0]

    # Langkah 2: Tentukan instruksi ke Ollama berdasarkan hasil ML
    if "tanpa bukti" in label and keyakinan > 0.55:
        instruksi = f"""
        User berkata: "{argumen_user}"
        ML mendeteksi ini adalah argumen lemah karena generalisasi tanpa konteks.
        Sebagai Krates, tanya SATU pertanyaan yang memancing user menemukan kelemahannya sendiri.
        Jangan langsung koreksi — tanya dulu.
        """
    else:
        instruksi = f"""
        User berkata: "{argumen_user}"
        ML mendeteksi ini adalah argumen yang mempertimbangkan konteks.
        Sebagai Krates, perdalam debatnya — tantang dari sudut pandang yang belum dipikirkan user.
        """

    return instruksi

# Test
argumen = "semua politisi itu koruptor"
instruksi = krates_berpikir(argumen)
print("Instruksi yang akan dikirim ke Ollama:")
print(instruksi)

def krates_berpikir(argumen_user):
    hasil_ml = krates_transformer(
        argumen_user,
        candidate_labels=[
            "pernyataan yang mempertimbangkan konteks dan alasan",
            "pernyataan yang menyimpulkan tanpa bukti atau konteks"
        ]
    )

    label = hasil_ml["labels"][0]
    keyakinan = hasil_ml["scores"][0]

    print(f"Debug — Label: {label}, Keyakinan: {keyakinan:.2%}")

    # Kalau keyakinan rendah (di bawah 65%), anggap argumen lemah
    # karena model tidak yakin = argumen butuh diperdalam
    if "tanpa bukti" in label or keyakinan < 0.65:
        instruksi = f"""
        User berkata: "{argumen_user}"
        Argumen ini terdeteksi lemah atau ambigu.
        Sebagai Krates, tanya SATU pertanyaan yang memancing user menemukan kelemahannya sendiri.
        Jangan langsung koreksi — tanya dulu.
        """
    else:
        instruksi = f"""
        User berkata: "{argumen_user}"
        Argumen ini mempertimbangkan konteks dengan baik.
        Sebagai Krates, perdalam debatnya dari sudut pandang yang belum dipikirkan user.
        """

    return instruksi

argumen = "semua politisi itu koruptor"
instruksi = krates_berpikir(argumen)
print("\nInstruksi ke Ollama:")
print(instruksi)

# !pip install pyngrok
from pyngrok import ngrok

# Buka tunnel ke Ollama di laptop kamu
# Tapi ini butuh Ollama jalan dulu di laptop

from pyngrok import ngrok

# Buka tunnel ke port Ollama
ngrok.set_auth_token("3H0fW90ecmoEf9JyVAxtvQZmAwB_2hbeJ3ujBF5kUKikU1J5Z")
tunnel = ngrok.connect(11434)
ollama_url = tunnel.public_url

print("URL Ollama:", ollama_url)

# Tutup tunnel lama dulu
ngrok.kill()

# Buat tunnel baru yang spesifik ke IPv4
from pyngrok.conf import PyngrokConfig
tunnel = ngrok.connect(
    addr="11434",
    proto="http"
)
ollama_url = tunnel.public_url
print("URL Ollama baru:", ollama_url)

import requests
import json

# Ensure krates_berpikir and ollama_url are defined in previous cells or globally
# krates_berpikir is assumed to be defined as in previous cells (e.g., IylCKEGZis04)
# ollama_url is assumed to be defined from ngrok.connect (e.g., 8ogEI3u34IeI)

def krates_respond(argumen_user):
    # krates_berpikir must be defined before this function is called.
    # Its definition is assumed to be from cell IylCKEGZis04
    instruksi = krates_berpikir(argumen_user)

    headers = {'Content-Type': 'application/json'}
    data = {
        "model": "llama3", # Ganti dengan model yang kamu pakai
        "prompt": instruksi,
        "stream": False
    }

    try:
        # Use the globally defined ollama_url
        response = requests.post(f"{ollama_url}/api/generate", headers=headers, data=json.dumps(data), timeout=60)
        response.raise_for_status() # Raise an exception for HTTP errors (4xx or 5xx)
        hasil = response.json()
        return hasil["message"]["content"]
    except requests.exceptions.Timeout:
        print("Error: Request to Ollama timed out.")
        return "Maaf, Ollama tidak merespons dalam waktu yang ditentukan."
    except requests.exceptions.RequestException as e:
        print(f"Error connecting to Ollama: {e}")
        print("Please ensure your Ollama server is running and accessible via ngrok.")
        return "Maaf, saya tidak bisa terhubung dengan Ollama saat ini."
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON from Ollama: {e}")
        print(f"Received non-JSON response content: {response.text}")
        return "Maaf, ada masalah dalam memproses respons dari Ollama (bukan JSON yang diharapkan)."
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return "Maaf, terjadi kesalahan yang tidak terduga."

argumen = "semua politisi itu koruptor"
print("User:", argumen)
print("\nKrates:", krates_respond(argumen))

